# Generated by Django 5.1.7 on 2025-04-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreriaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateField(null=True),
        ),
    ]
