version: '3.8'

services:

  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    container_name: postgres_containerLIB
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=libreriadb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Caasd21215@@

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_containerLIB
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@example.com"
      PGADMIN_DEFAULT_PASSWORD: "Caasd21215@@"
    ports:
      - "8082:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
  
  redis:
    container_name: redis_LIB
    image: redis:latest
    ports:
      - "8081:6379"
  web:
    build: .
    container_name: libreria_container
    command: python libreriaR/manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_local
    restart: always
    ports:
      - "5678:5678"
    environment:
      N8N_HOST: localhost 
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      
      WEBHOOK_URL: http://localhost:5678/
      
      N8N_BASIC_AUTH_ACTIVE: 'true'
      N8N_BASIC_AUTH_USER: 'admin'
      N8N_BASIC_AUTH_PASSWORD: 'Caasd21215@@'
    
    volumes:
      - n8n_data:/home/node/.n8n


volumes:
  postgres_data:
  pgadmin_data:
  n8n_data: